[project]
name = "subcad"
version = "0.1.0"
description = ""
authors = [
    {name = "abdkarr",email = "7543956+abdkarr@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,!=3.14.1"
dependencies = [
    "numpy>=1.26,<2.5",
    "scipy>=1.14",
    "numba>=0.60",
    "networkx>=3.3",
    "pandas>=2.2",
    "requests>=2.32",
    "scikit-learn>=1.5",
]

[project.optional-dependencies]
experiments = [
    "crowd-kit>=1.4",
    "click>=8.1",
    "matplotlib>=3.9",
    "seaborn>=0.13",
]
docs = [
    "zensical>=0.0.48",
    "mkdocstrings-python>=2.0",
]

[tool.poetry]
packages = [{include = "subcad", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
